# Generated by Django 2.1.2 on 2018-10-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giphy_id', models.CharField(max_length=255)),
                ('giphy_url', models.URLField()),
                ('giphy_embed_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TagSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gifs.TagSource'),
        ),
        migrations.AddField(
            model_name='gif',
            name='giphy_tags',
            field=models.ManyToManyField(to='gifs.Tag'),
        ),
    ]
