# Generated by Django 2.1.2 on 2018-10-30 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gifs', '0002_auto_20181029_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gif',
            name='giphymodel_ptr',
        ),
        migrations.AddField(
            model_name='gif',
            name='favorited_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gif',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GiphyModel',
        ),
    ]
