# Generated by Django 2.1.2 on 2018-10-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifs', '0004_auto_20181030_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='giphy_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
